# syntax=docker/dockerfile:1

# ---------------------------------------------------------------------------
# Stage 1: Composer dependencies + Wayfinder code generation
#
# Uses the same base image and the same PHP extension set as the runtime stage
# so `composer install` evaluates the exact same platform requirements.
# ---------------------------------------------------------------------------
FROM php:8.4-fpm-alpine AS php-builder

RUN apk add --no-cache \
    libpng-dev \
    libjpeg-turbo-dev \
    freetype-dev \
    libzip-dev \
    icu-dev \
    unzip \
    git

RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) \
        pdo_mysql \
        bcmath \
        zip \
        opcache \
        gd \
        intl

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

# composer.lock must be named explicitly: the previous "composer*.json" glob
# never matched it, so the build resolved dependencies from scratch.
COPY composer.json composer.lock ./
RUN composer install \
    --no-dev \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --prefer-dist \
    --optimize-autoloader

COPY . .

# resources/js/{actions,routes,wayfinder} are gitignored and generated by
# `php artisan wayfinder:generate`. Doing it here (instead of relying on the
# Vite plugin) keeps the Node stage free of a PHP runtime.
RUN php artisan wayfinder:generate --with-form

# ---------------------------------------------------------------------------
# Stage 2: Build frontend assets (Inertia React + Vite)
# ---------------------------------------------------------------------------
FROM node:22-alpine AS node-builder

WORKDIR /app

# Vite inlines import.meta.env.VITE_APP_NAME at build time and .env files are
# excluded from the build context, so the value has to arrive as a build arg.
ARG VITE_APP_NAME
ENV VITE_APP_NAME=${VITE_APP_NAME}

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# Wayfinder output is generated in the php-builder stage above.
COPY --from=php-builder /app/resources/js/actions ./resources/js/actions
COPY --from=php-builder /app/resources/js/routes ./resources/js/routes
COPY --from=php-builder /app/resources/js/wayfinder ./resources/js/wayfinder

# @laravel/vite-plugin-wayfinder shells out to `php artisan wayfinder:generate`
# during buildStart and fails the whole build when that command is missing.
# The files are already generated and copied in above, so satisfy the plugin
# with a no-op shim rather than installing a second PHP runtime here.
RUN printf '#!/bin/sh\nexit 0\n' > /usr/local/bin/php && chmod +x /usr/local/bin/php

RUN npm run build

# ---------------------------------------------------------------------------
# Stage 3: Production environment (PHP 8.4 + Nginx + Supervisor)
# ---------------------------------------------------------------------------
FROM php:8.4-fpm-alpine

WORKDIR /var/www/html

# Install system dependencies
RUN apk add --no-cache \
    nginx \
    supervisor \
    libpng-dev \
    libjpeg-turbo-dev \
    freetype-dev \
    libzip-dev \
    icu-dev \
    zip \
    unzip \
    bash \
    mysql-client

# Configure and install PHP extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) \
        pdo_mysql \
        bcmath \
        zip \
        opcache \
        gd \
        intl

# Configure PHP production settings
RUN { \
        echo 'memory_limit = 512M'; \
        echo 'upload_max_filesize = 64M'; \
        echo 'post_max_size = 64M'; \
        echo 'max_execution_time = 300'; \
    } > /usr/local/etc/php/conf.d/docker-php-custom.ini

# Copy Nginx and Supervisor configs
COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Copy application files
COPY --chown=www-data:www-data . .

# Copy built assets and vendor dependencies from previous stages
COPY --from=node-builder --chown=www-data:www-data /app/public/build ./public/build
COPY --from=php-builder --chown=www-data:www-data /app/vendor ./vendor

# Optimize Composer Autoload
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
RUN composer dump-autoload --no-dev --classmap-authoritative

# Ensure storage and bootstrap/cache directories are writable
RUN mkdir -p storage/framework/{sessions,views,caches} \
    && chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache \
    && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache

# Copy entrypoint script
COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
